### PR TITLE
WIP Calculations wiki branch

### PR DESCRIPTION
**Pull request by kylebystrom**
I've completed the calculations-wiki, calculation-manual, gga-plus-u, pseudopotentials, and elasticity pages. There might still be a couple minor errors which I will revise as I add more pages, and calculations-wiki has a few broken links since those pages don't exist yet.

### CODE REVIEW

**Comment by kylebystrom** [comment]
Still WIP, but I've added all the files and figures at this point. Just need to go through each page and proofread/check links now.

**Comment by kylebystrom** [comment]
@tschaume should I proofread the grammar for these pages and split the "Calculation Manual" into the "Total Energies" and "Band structure" sections as in the mkdocs nav bar? Or should I just have provide an exact copy of the wiki for now?

**Comment by tschaume** [comment]
@kylebystrom it would be great if you could proof-read it and double check if there are entries elsewhere in the docs referring to the "total energies" and "band structure" sections. It's up to you if you want to separate them out or just update the links in the other parts of the docs.

**Comment by kylebystrom** [comment]
@tschaume This PR is ready to go now. I proofread the files and made some changes for grammar/clarity, though I erred on the side of leaving things the same if I wasn't 100% sure if I might accidentally change the meaning etc. Note this PR does NOT include anything under the "Error Checking Wiki" header on the original wiki. That's assigned in #6 . I split "calculation-manual.md" into "total-energies.md" and "electronic-structure.md" and removed "calculation-wiki.md", since that was basically just the nav bar.

**Comment by kylebystrom** [comment]
Yes, sorry I forgot to mention that. That's a page under the "Error Checking Wiki," but I added a blank page for it because "total-energies.md" links to it, and I didn't want the link to be broken.

**Pull request merged**
