### PR TITLE
Target solubility tool

### PR DESCRIPTION
**Pull request by kylebystrom**
For #18

### CODE REVIEW

**Comment by kylebystrom** [comment]
This is for #5

**Comment by kylebystrom** [comment]
This is for #18

**Comment by kylebystrom** [comment]
Hi @tschaume I did the target solubility tool page, sorry I forgot to tag you yesterday.

**Comment by dwinston** [comment]
Oh darn, I'm sorry about this @kylebystrom but "target solutibility tool" is the old name for the redox flow battery (RFB) dashboard. We should have deleted that wiki page. You will notice that the two wiki pages are similar, nearly identical. We only wanted to migrate in the RFB dashboard page, which it looks like @acrutt did in #33. Again, sorry.

**Pull request closed without merging**
